### ISSUE TITLE
Specify public key formats from the DID spec

### ISSUE THREAD

**Issue by rhiaro** [w3c-ccg/ld-cryptosuite-registry#10]
See list in https://w3c-ccg.github.io/did-spec/#public-keys

Suggestion by @AxelNennker in https://github.com/w3c-ccg/did-spec/pull/162#issuecomment-458967382

**Comment by AxelNennker** [comment]
I mean item 6 'A registry of key types and formats is available in Appendix § A. Registries.'
The key formats are not defined in the registry.

**Comment by OR13** [comment]
I believe this is the case today... suggest closing or making this issue actionable.
