### ISSUE TITLE
Add controller to registry key examples.

### ISSUE THREAD

**Issue by aljones15** [w3c-ccg/ld-cryptosuite-registry#13]
While not required by the registry currently publicKey objects in the DID v 0.13 require a controller property to be defined:

> Each public key MUST include a controller property, which identifies the controller of the corresponding private key.

Hence I think the examples in the registry should be updated to include it in order to avoid confusion.

https://w3c-ccg.github.io/did-spec/#generic-did-syntax

**Comment by dmitrizagidulin** [comment]
This has been addressed in a previous commit; closing.
