### ISSUE TITLE
Ensure registry communicates 1:1 combination of key+signature type

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/ld-cryptosuite-registry#15]
One thing we need to be careful about in how we present/list keys and signature types is in accidentally suggesting that the verification methods are decoupled from the signature types; they aren't. There is a 1:1 binding between verification method and signature type. It's fine to do whatever we need for presentation purposes, but we intentionally baked in this binding to prevent people from mixing and matching as it's a security threat.

**Comment by dmitrizagidulin** [comment]
Addressed by PR #19, closing.
