### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by llorllale** [w3c-ccg/ld-cryptosuite-registry#23]
Links to the following suites no longer work:

* Ed25519Signature2018
* Ed25519VerificationKey2018
* RsaSignature2018

**Comment by peacekeeper** [comment]
This was fixed by https://github.com/w3c-ccg/ld-cryptosuite-registry/pull/24 in https://github.com/w3c-ccg/ld-cryptosuite-registry/pull/24/commits/acd81a59f19eaea2eba09af1f743f38b5c7d6c7a.
