### ISSUE TITLE
publicKeyHex is widely used but not supported by did-core

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/ld-cryptosuite-registry#28]
Regardless of feeling on this... many have implemented support for `publicKeyHex` it is defined by https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/

And the example in this registry contains `publicKeyHex`... we need to remove this property from everywhere, or add support for it.... This is mostly a did core issue...

https://github.com/w3c/did-core/issues/236

**Comment by kdenhartog** [comment]
I think we can close this now that it's registered in the did-spec-registries. Would we want to cross register it here as well and just update the definition etc? https://w3c.github.io/did-spec-registries/#publickeyhex

**Comment by OR13** [comment]
yes we can close.
