### ISSUE TITLE
Update language to sync with pending DID method registry PR

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/ld-cryptosuite-registry#6]
https://github.com/w3c-ccg/did-method-registry/pull/6 has some language we probably want to adopt regarding conformance and public access to specification.

Once that PR is pulled in (whatever the edits end up being), we should sync the language of this registry.

**Comment by msporny** [comment]
> Once that PR is pulled in (whatever the edits end up being), we should sync the language of this registry.

Done in 7ae56cc903ed2168e654a90b888e1a49460fdf47 and 56518f26de24d2f04ca58f57e0507c6274f40ac2. Let me know if the updates work for you @jandrieu ... up to you to close the issue or do some editorial clean up.

**Comment by OR13** [comment]
@jandrieu can you review and close this issue or add an update so that someone in the community can tackle it.

**Comment by jandrieu** [comment]
LGTM. Closing.
