### ISSUE TITLE
Add Secp256k1VerificationKey2018 to the Linked Data Cryptographic Suite Registry

### ISSUE THREAD

**Issue by gjgd** [w3c-ccg/ld-cryptosuite-registry#9]
[The Registry](https://w3c-ccg.github.io/ld-cryptosuite-registry/#the-registry) that lists all Linked Data key types known to the community should include "Secp256k1VerificationKey2018" type, used in [Uport specs](https://github.com/uport-project/ethr-did) and [Bitcoin specs (page 4)](https://www.w3.org/2018/vocabws/presentations/Sabadello.pdf)

I suggest we had a `3.4 Secp256k1VerificationKey2018` entry with the example
```
{
  id: 'did:ethr:b9c5714089478a327f09197987f16f9e5d936e8a#owner',
  type: 'Secp256k1VerificationKey2018',
  owner: 'did:ethr:b9c5714089478a327f09197987f16f9e5d936e8a',
  publicKeyHex: 'b9c5714089478a327f09197987f16f9e5d936e8a'
}
```

**Comment by awoie** [comment]
uPort uses `Secp256k1VerificationKey2018` but having `ethereumAddress` instead of `publicKeyHex` which I believe might not be supported in the spec for now. @christianlundkvist could you provide more input on that because I'm lacking a bit from context of what has been discussed so far?
